config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  root to: "home#index"
  resources :users
  resources :books

  get  'home/about'

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  attachment :image
  belongs_to :user

  with_options presence: true do
    validates :title
    validates :body
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  attachment :profile_image

  validates :username, presence: true

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.username = "ゲスト"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  PER = 6
  
  def new
    @book = Book.new
  end
  
  def create
    @book = current_user.books.build(book_params)
    if @book.save
      redirect_to book_path(@book), notice: "感想を投稿しました。"
    else
      render :new
    end
  end
  
  def index
    @books = Book.page(params[:page]).per(PER)
  end
  
  def show
    @book = Book.find(params[:id])
  end
  
  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
        redirect_to books_path, alert: "不正なアクセスです。"
    end
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "感想を更新しました。"
    else
      render :edit
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to user_path(book.user), notice: "感想を削除しました。"
  end

  private
  
  def book_params
    params.require(:book).permit(:title, :body, :image, :comment)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def about
  end

end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  before_action :ensure_normal_user, only: :create

  def ensure_normal_user
    if params[:user][:email].downcase == 'guest@example.com'
      redirect_to new_user_session_path, alert: 'ゲストユーザーのパスワード再設定はできません。'
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :ensure_normal_user, only: %i[update destroy]

  def ensure_normal_user
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの更新・削除はできません。'
    end
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :authenticate_user!, except: [:index]
  PER = 8
 
  def index
    @users = User.page(params[:page]).per(PER)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
        redirect_to user_path(current_user), alert: "不正なアクセスです。"
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "ユーザー情報を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path, notice: "ユーザー情報を削除しました。"
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        読書感想編集
      </h1>
    </div>
  </div>
</section>

<% if @book.errors.any? %>
  <div class="notification is-primary">
    <h2><%= pluralize(@book.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @book do |f| %>
          <div class="field">
            <%= f.label :title, "タイトル", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "感想", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>

          <%= f.submit '投稿', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/books/index.html.erb
<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        読書感想一覧
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @books.each do |book| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to book_path(book) do %>
                  <%= attachment_image_tag book, :image, fallback: "no-image.png", class: "fit_image" %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-left">
                  <figure class="image is-48x48">
                    <%= attachment_image_tag book.user, :profile_image, fallback: "no-image_prof.png", class: "profile_image" %>
                  </figure>
                </div>
                <div class="media-content">
                  <div class="title"><%=link_to book.user.username, user_path(book.user) %></div>
                </div>
              </div>

              <div class="content">
                <time><%= book.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <br>
  <br>
  <div class="column is-half is-offset-one-quarter">
  <%= paginate @books %>
  </div>
</section>

app/views/books/new.html.erb
<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        読書感想投稿
      </h1>
    </div>
  </div>
</section>


<% if @book.errors.any? %>
  <div class="notification is-primary">
    <h2><%= pluralize(@book.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @book do |f| %>
          <div class="field">
            <%= f.label :title, "タイトル", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "感想", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>

          <%= f.submit '投稿', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/books/show.html.erb
<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        読書感想詳細
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-7">
        <div class="card">
          <div class="card-image">
            <figure class="image is-4by3">
              <%= attachment_image_tag @book, :image, fallback: "no-image.png", class: "fit_image" %>
            </figure>
          </div>
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <p class="title is-4"><%= @book.title %></p>
              </div>
            </div>
            <div class="content">
              <table class="table is-narrow">
                <tr>
                  <th>読書感想</th>
                </tr>
                <tr>
                  <td><%= simple_format @book.body %></td>
                </tr>
              </table>
              <% if @book.user.id == current_user.id %>
                <%= link_to "編集画面へ", edit_book_path(@book), class: "button is-success" %>
              <% end %>
              <% if @book.user.id == current_user.id %>
                <%= link_to "削除する", book_path(@book), method: :delete, data: {confirm: "削除しますか？"}, class: "button is-success" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="column is-4">
        <article class="panel is-primary">
          <p class="panel-heading">
            By <%= @book.user.username %>
          </p>
          <div class="panel-block">
            <p class="control">
              <%= @book.user.profile %>
            </p>
          </div>
          <%= link_to user_path(@book.user), class: "panel-block" do %>
            <span class="panel-icon">
              <i class="fas fa-user" aria-hidden="true"></i>
            </span>
            <%= @book.user.username %> さんのページへ
          <% end %>
        </article>
      </div>
    </div>
  </div>
</section>

app/views/home/about.html.erb
<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        このページについて
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    読書感想を投稿できるＳＮＳです。
    <br>
    Ruby on Railsを使用して作成しています。
    <br>
    <br>
    基本的にログインしないと機能が使用できないようになっていますので、
    <br>
    ユーザー登録が面倒であれば、<%= link_to '簡単ログイン', users_guest_sign_in_path, method: :post %>を使用するようお願いいたします。
    <br>
    ※スマホ非対応です。
    <br>
  </div>
</section>

app/views/home/index.html.erb
<section class="hero">
  <div class="hero-body">
    <div class="content has-text-centered">
      <h1 class="title">
          <strong class="is-size-1 title_font">読書感想投稿ＳＮＳ</strong>
      </h1>
    </div>
  </div>
</section>
      <% if user_signed_in? %>
        <div class="columns is-centered">
          <div class="column is-5">
            <br>
            <br>
            <%= link_to "このページについて", home_about_url, class: "button is-fullwidth" %>
            <br>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "button is-fullwidth" %>
          </div>
        </div>
      <% else %>
        <div class="columns is-centered">
          <div class="column is-5">
            <br>
            <%= link_to "ログイン", new_user_session_path, class: "button is-fullwidth" %>
            <br>
            <%= link_to "新規登録", new_user_registration_path, class: "button is-fullwidth" %>
            <br>
            <%= link_to '簡単ログイン', users_guest_sign_in_path, method: :post, class: "button is-fullwidth" %>
            <br>
            <%= link_to "このページについて", home_about_url, class: "button is-fullwidth" %>
          </div>
        </div>
      <% end %>
    </div>
  </article>
  <br>
  <div class="columns is-centered">
    <div class="column">
      <figure>
        <div class="main-image"></div>
      </figure>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>読書感想投稿ＳＮＳ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('favicon.png') %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-primary">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <nav class="navbar">
      <div class="navbar-brand">
          <h1><%= link_to image_tag("logo.png", alt: "SHIORI logo", style: "height: 40px;"),root_path %></h1>
        <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <% if user_signed_in? %>
        <div id="navbarExampleTransparentExample" class="navbar-menu">
          <div class="navbar-item">
            <%= link_to "読書感想一覧", books_path, class: "button is-small" %>
          </div>
          <div class="navbar-item">
            <%= link_to "読書感想投稿", new_book_path, class: "button is-small" %>
          </div>

          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to "ユーザー一覧", users_path, class: "button is-small" %>
                </p>
                <p class="control">
                  <%= link_to "マイページ", user_path(current_user), class: "button is-small" %>
                </p>
                <p class="control">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "button is-small" %>
                </p>
                <p class="control">
                  <%= link_to "このページについて", home_about_url, class: "button is-small" %>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <div id="navbarExampleTransparentExample" class="navbar-menu">
          <div class="navbar-item">
            <%= link_to "読書感想一覧", books_path, class: "button is-small" %>
          </div>
          <div class="navbar-item">
            <%= link_to "ユーザー一覧", users_path, class: "button is-small" %>
          </div>
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to "ログイン", new_user_session_path, class: "button is-small" %>
                </p>
                <p class="control">
                  <%= link_to "新規登録", new_user_registration_path, class: "button is-small" %>
                </p>
                <p class="control">
                  <%= link_to '簡単ログイン', users_guest_sign_in_path, method: :post, class: "button is-small" %>
                </p>
                <p class="control">
                  <%= link_to "このページについて", home_about_url, class: "button is-small" %>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% end %>

    </nav>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ユーザー編集
      </h1>
    </div>
  </div>
</section>


<% if @user.errors.any? %>
  <div class="notification is-primary">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @user do |f| %>
          <div class="field">
            <%= f.label :username, "ユーザー名", class: "label" %>
            <%= f.text_field :username, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :email, "メールアドレス", class: "label" %>
            <%= f.email_field :email, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :profile, "プロフィール", class: "label" %>
            <%= f.text_area :profile, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :profile_image, "プロフィール画像", class: "label" %>
            <%= f.attachment_field :profile_image, class: "input" %>
          </div>

          <%= f.submit "更新", class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ユーザー一覧
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @users.each do |user| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-content">
              <div class="card-image">
                <figure class="image">
                  <%= link_to user_path(user) do %>
                    <%= attachment_image_tag user, :profile_image, fallback: "no-image_prof.png" %>
                  <% end %>
                </figure>
              </div>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="title"><%=link_to user.username, user_path(user) %></div>
                </div>
              </div>
              <div class="content">
                投稿数：<%= user.books.count %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <br>
  <br>
  <div class="column is-half is-offset-one-quarter">
    <%= paginate @users %>
  </div>
</section>

app/views/users/show.html.erb
<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        マイページ
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-10">
        <div class="columns is-centered">
          <div class="column is-4">
            <figure class="image is-128x128"  style="margin-left: auto; margin-right: auto;">
              <%= attachment_image_tag @user, :profile_image, fallback: "no-image_prof.png", class: "profile_image is-rounded" %>
            </figure>
          </div>
          <div class="column is-8">
            <table class="table is-fullwidth">
              <tr>
                <td class="is-size-4">
                  <strong><%= @user.username %></strong>
                </td>
                <% if @user.id == current_user.id %>
                <td class="is-size-4">
                  <%= @user.email %>
                </td>
                <td>
                    <%= link_to "編集", edit_user_path(@user), class: "button is-primary" %>
                </td>
                <td>
                    <%= link_to "削除",user_path(@user), method: :delete, data: {confirm: "ユーザーを削除しますか？"}, class: "button is-primary" %>
                </td>
                <% end %>
              </tr>
            </table>
            <table class="table is-fullwidth">
              <tr>
                <td>
                  <%= @user.profile %>
                </td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @user.books.each do |book| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to book_path(book) do %>
                  <%= attachment_image_tag book, :image, fallback: "no-image.png", class: "fit_image" %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <%= link_to book_path(book), class: "panel-block" do %>
                    <span class="panel-icon">
                      <i class="fas fa-book" aria-hidden="true"></i>
                    </span>
                    この本の感想を見る
                  <% end %>
                  <% if @user.id == current_user.id %>
                    <%= link_to edit_book_path(book), class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-edit"></i>
                      </span>
                      この本の感想を編集する
                    <% end %>
                    <%= link_to book_path(book), method: :delete, data: {confirm: "削除しますか？"}, class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-trash"></i>
                      </span>
                      この本の感想を削除する
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="content">
                <time><%= book.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>